version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r Lambda/requirements.txt

  build:
    commands:
      - echo "Running unit tests..."
      - pip install pytest moto
      - pytest -q tests/unit || true
      - pytest -q tests/Integration || true

artifacts:
  files:
    - '**/*'