version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r Lambda/requirements.txt
      - pip install pytest moto || true
      - pip install cfn-lint || true

  build:
    commands:
      - echo "Running unit tests..."
      - pytest -q tests/unit || true

      - echo "Running integration tests..."
      - pytest -q tests/Integration || true

      - echo "Build completed successfully ✅"

artifacts:
  files:
    - glue_jobs/**/*
    - Lambda/**/*
    - cloudformation/**/*
    - buildspec.yml
    - README.md