AWSTemplateFormatVersion: "2010-09-09"
Description: Netflix DataLake Automation with Auto-Cleanup - S3 -> EventBridge -> Glue Workflows (Silver + Gold)

Parameters:
  BucketName:
    Type: String
    Default: netflix-raw-123456-dev

  RawPrefix:
    Type: String
    Default: netflix-raw/

  SilverPrefix:
    Type: String
    Default: netflix/silver/

  GoldPrefix:
    Type: String
    Default: netflix/gold/

  SilverDatabase:
    Type: String
    Default: netflix_db

  GoldDatabase:
    Type: String
    Default: gold_db

  SilverTableName:
    Type: String
    Default: netflix_raw

  GoldTableName:
    Type: String
    Default: silver

  SilverJobName:
    Type: String
    Default: netflix-sliver-job

  GoldJobName:
    Type: String
    Default: netflix-gold-job

  SilverCrawlerName:
    Type: String
    Default: sliver_converion_crawler

  GoldCrawlerName:
    Type: String
    Default: gold_conversion_crawler

  SilverWorkflowName:
    Type: String
    Default: Silver_workflow

  GoldWorkflowName:
    Type: String
    Default: Gold_workflow

  ScriptLocationPrefix:
    Type: String
    Default: scripts/

  SilverJobScriptKey:
    Type: String
    Default: scripts/sliver_job.py

  GoldJobScriptKey:
    Type: String
    Default: scripts/gold_job.py

Resources:

  # -----------------------------
  # Lambda Execution Role for Cleanup
  # -----------------------------
  CleanupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CleanupResourcesPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:DeleteTrigger
                  - glue:DeleteWorkflow
                  - glue:DeleteCrawler
                  - glue:DeleteJob
                  - glue:DeleteDatabase
                  - glue:GetTrigger
                  - glue:GetWorkflow
                  - glue:GetCrawler
                  - glue:GetJob
                  - glue:GetDatabase
                  - events:DeleteRule
                  - events:RemoveTargets
                  - events:ListTargetsByRule
                  - events:DescribeRule
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:GetRole
                  - iam:ListRolePolicies
                Resource: "*"

  # -----------------------------
  # Lambda Function for Cleanup
  # -----------------------------
  CleanupLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: NetflixDataLakeCleanup
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt CleanupLambdaRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          glue = boto3.client('glue')
          events = boto3.client('events')
          iam = boto3.client('iam')
          
          def lambda_handler(event, context):
              logger.info(f"Event: {event}")
              
              try:
                  if event['RequestType'] == 'Delete':
                      # Don't do anything on stack deletion
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  resources_to_clean = event['ResourceProperties']
                  
                  # Delete Glue Triggers
                  for trigger in resources_to_clean.get('Triggers', []):
                      try:
                          glue.delete_trigger(Name=trigger)
                          logger.info(f"Deleted Trigger: {trigger}")
                      except glue.exceptions.EntityNotFoundException:
                          logger.info(f"Trigger not found: {trigger}")
                      except Exception as e:
                          logger.warning(f"Error deleting trigger {trigger}: {str(e)}")
                  
                  # Delete Glue Workflows
                  for workflow in resources_to_clean.get('Workflows', []):
                      try:
                          glue.delete_workflow(Name=workflow)
                          logger.info(f"Deleted Workflow: {workflow}")
                      except glue.exceptions.EntityNotFoundException:
                          logger.info(f"Workflow not found: {workflow}")
                      except Exception as e:
                          logger.warning(f"Error deleting workflow {workflow}: {str(e)}")
                  
                  # Delete Glue Crawlers
                  for crawler in resources_to_clean.get('Crawlers', []):
                      try:
                          glue.delete_crawler(Name=crawler)
                          logger.info(f"Deleted Crawler: {crawler}")
                      except glue.exceptions.EntityNotFoundException:
                          logger.info(f"Crawler not found: {crawler}")
                      except Exception as e:
                          logger.warning(f"Error deleting crawler {crawler}: {str(e)}")
                  
                  # Delete Glue Jobs
                  for job in resources_to_clean.get('Jobs', []):
                      try:
                          glue.delete_job(JobName=job)
                          logger.info(f"Deleted Job: {job}")
                      except glue.exceptions.EntityNotFoundException:
                          logger.info(f"Job not found: {job}")
                      except Exception as e:
                          logger.warning(f"Error deleting job {job}: {str(e)}")
                  
                  # Delete Glue Databases
                  for database in resources_to_clean.get('Databases', []):
                      try:
                          glue.delete_database(Name=database)
                          logger.info(f"Deleted Database: {database}")
                      except glue.exceptions.EntityNotFoundException:
                          logger.info(f"Database not found: {database}")
                      except Exception as e:
                          logger.warning(f"Error deleting database {database}: {str(e)}")
                  
                  # Delete EventBridge Rules
                  for rule in resources_to_clean.get('EventRules', []):
                      try:
                          # Remove targets first
                          targets_response = events.list_targets_by_rule(Rule=rule)
                          target_ids = [t['Id'] for t in targets_response.get('Targets', [])]
                          if target_ids:
                              events.remove_targets(Rule=rule, Ids=target_ids)
                          
                          # Delete rule
                          events.delete_rule(Name=rule)
                          logger.info(f"Deleted EventBridge Rule: {rule}")
                      except events.exceptions.ResourceNotFoundException:
                          logger.info(f"EventBridge Rule not found: {rule}")
                      except Exception as e:
                          logger.warning(f"Error deleting rule {rule}: {str(e)}")
                  
                  # Delete IAM Roles
                  for role in resources_to_clean.get('IAMRoles', []):
                      try:
                          # Delete inline policies
                          policies = iam.list_role_policies(RoleName=role)
                          for policy in policies.get('PolicyNames', []):
                              iam.delete_role_policy(RoleName=role, PolicyName=policy)
                          
                          # Delete role
                          iam.delete_role(RoleName=role)
                          logger.info(f"Deleted IAM Role: {role}")
                      except iam.exceptions.NoSuchEntityException:
                          logger.info(f"IAM Role not found: {role}")
                      except Exception as e:
                          logger.warning(f"Error deleting role {role}: {str(e)}")
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                      'Message': 'Cleanup completed successfully'
                  })
                  
              except Exception as e:
                  logger.error(f"Error in cleanup: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {
                      'Message': str(e)
                  })

  # -----------------------------
  # Custom Resource to Trigger Cleanup
  # -----------------------------
  CleanupCustomResource:
    Type: Custom::CleanupResources
    Properties:
      ServiceToken: !GetAtt CleanupLambdaFunction.Arn
      Triggers:
        - SilverTriggerCrawler
        - SilverTriggerJob
        - GoldTriggerCrawler
        - GoldTriggerJob
      Workflows:
        - !Ref SilverWorkflowName
        - !Ref GoldWorkflowName
      Crawlers:
        - !Ref SilverCrawlerName
        - !Ref GoldCrawlerName
      Jobs:
        - !Ref SilverJobName
        - !Ref GoldJobName
      Databases:
        - !Ref SilverDatabase
        - !Ref GoldDatabase
      EventRules:
        - RawUploadTriggerSilverRule
        - SilverSuccessTriggerGoldRule
      IAMRoles:
        - NetflixGlueServiceRole
        - NetflixEventBridgeInvokeGlueRole

  # -----------------------------
  # IAM Role for Glue
  # -----------------------------
  GlueServiceRole:
    Type: AWS::IAM::Role
    DependsOn: CleanupCustomResource
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: NetflixGlueS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

  # -----------------------------
  # Glue Databases
  # -----------------------------
  SilverGlueDatabase:
    Type: AWS::Glue::Database
    DependsOn: CleanupCustomResource
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref SilverDatabase

  GoldGlueDatabase:
    Type: AWS::Glue::Database
    DependsOn: CleanupCustomResource
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref GoldDatabase

  # -----------------------------
  # Silver Crawler
  # -----------------------------
  SilverCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: CleanupCustomResource
    Properties:
      Name: !Ref SilverCrawlerName
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref SilverDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${BucketName}/${RawPrefix}
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE

  # -----------------------------
  # Gold Crawler
  # -----------------------------
  GoldCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: CleanupCustomResource
    Properties:
      Name: !Ref GoldCrawlerName
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GoldDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${BucketName}/${SilverPrefix}
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE

  # -----------------------------
  # Silver Glue Job
  # -----------------------------
  SilverGlueJob:
    Type: AWS::Glue::Job
    DependsOn: CleanupCustomResource
    Properties:
      Name: !Ref SilverJobName
      Role: !GetAtt GlueServiceRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/${SilverJobScriptKey}
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub s3://${BucketName}/sparkHistoryLogs/
      ExecutionProperty:
        MaxConcurrentRuns: 1
      WorkerType: G.1X
      NumberOfWorkers: 2

  # -----------------------------
  # Gold Glue Job
  # -----------------------------
  GoldGlueJob:
    Type: AWS::Glue::Job
    DependsOn: CleanupCustomResource
    Properties:
      Name: !Ref GoldJobName
      Role: !GetAtt GlueServiceRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/${GoldJobScriptKey}
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub s3://${BucketName}/sparkHistoryLogs/
      ExecutionProperty:
        MaxConcurrentRuns: 1
      WorkerType: G.1X
      NumberOfWorkers: 2

  # -----------------------------
  # Glue Workflow Silver
  # -----------------------------
  SilverWorkflow:
    Type: AWS::Glue::Workflow
    DependsOn: CleanupCustomResource
    Properties:
      Name: !Ref SilverWorkflowName

  # Workflow Triggers for Silver
  SilverTriggerCrawler:
    Type: AWS::Glue::Trigger
    DependsOn: CleanupCustomResource
    Properties:
      Name: SilverTriggerCrawler
      Type: ON_DEMAND
      WorkflowName: !Ref SilverWorkflowName
      Actions:
        - CrawlerName: !Ref SilverCrawlerName

  SilverTriggerJob:
    Type: AWS::Glue::Trigger
    DependsOn: 
      - SilverCrawler
      - CleanupCustomResource
    Properties:
      Name: SilverTriggerJob
      Type: CONDITIONAL
      WorkflowName: !Ref SilverWorkflowName
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref SilverCrawlerName
            CrawlState: SUCCEEDED
      Actions:
        - JobName: !Ref SilverJobName

  # -----------------------------
  # Glue Workflow Gold
  # -----------------------------
  GoldWorkflow:
    Type: AWS::Glue::Workflow
    DependsOn: CleanupCustomResource
    Properties:
      Name: !Ref GoldWorkflowName

  GoldTriggerCrawler:
    Type: AWS::Glue::Trigger
    DependsOn: CleanupCustomResource
    Properties:
      Name: GoldTriggerCrawler
      Type: ON_DEMAND
      WorkflowName: !Ref GoldWorkflowName
      Actions:
        - CrawlerName: !Ref GoldCrawlerName

  GoldTriggerJob:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GoldCrawler
      - CleanupCustomResource
    Properties:
      Name: GoldTriggerJob
      Type: CONDITIONAL
      WorkflowName: !Ref GoldWorkflowName
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref GoldCrawlerName
            CrawlState: SUCCEEDED
      Actions:
        - JobName: !Ref GoldJobName

  # -----------------------------
  # IAM Role for EventBridge to start Glue Workflows
  # -----------------------------
  EventBridgeInvokeGlueRole:
    Type: AWS::IAM::Role
    DependsOn: CleanupCustomResource
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowStartGlueWorkflow
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartWorkflowRun
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${SilverWorkflowName}
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${GoldWorkflowName}

  # -----------------------------
  # EventBridge Rule #1 RAW Upload -> Silver Workflow
  # -----------------------------
  RawUploadTriggerSilverRule:
    Type: AWS::Events::Rule
    DependsOn: CleanupCustomResource
    Properties:
      Name: RawUploadTriggerSilverRule
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref BucketName
          object:
            key:
              - prefix: !Ref RawPrefix
      Targets:
        - Arn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${SilverWorkflowName}
          Id: StartSilverWorkflow
          RoleArn: !GetAtt EventBridgeInvokeGlueRole.Arn

  # -----------------------------
  # EventBridge Rule #2 Silver Marker -> Gold Workflow
  # -----------------------------
  SilverSuccessTriggerGoldRule:
    Type: AWS::Events::Rule
    DependsOn: CleanupCustomResource
    Properties:
      Name: SilverSuccessTriggerGoldRule
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref BucketName
          object:
            key:
              - prefix: !Sub ${SilverPrefix}_SUCCESS
      Targets:
        - Arn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${GoldWorkflowName}
          Id: StartGoldWorkflow
          RoleArn: !GetAtt EventBridgeInvokeGlueRole.Arn

Outputs:
  SilverWorkflowOut:
    Value: !Ref SilverWorkflowName
    Description: Silver Glue Workflow Name

  GoldWorkflowOut:
    Value: !Ref GoldWorkflowName
    Description: Gold Glue Workflow Name
  
  GlueServiceRoleArn:
    Value: !GetAtt GlueServiceRole.Arn
    Description: ARN of the Glue Service Role
  
  EventBridgeRoleArn:
    Value: !GetAtt EventBridgeInvokeGlueRole.Arn
    Description: ARN of the EventBridge Role
  
  CleanupFunctionArn:
    Value: !GetAtt CleanupLambdaFunction.Arn
    Description: ARN of the Cleanup Lambda Function