AWSTemplateFormatVersion: "2010-09-09"
Description: Netflix DataLake Automation - S3 -> CloudTrail -> EventBridge -> Glue Workflows (Silver + Gold)

Parameters:
  BucketName:
    Type: String
    Default: netflix-raw-123456-dev

  RawPrefix:
    Type: String
    Default: netflix-raw/

  SilverPrefix:
    Type: String
    Default: netflix/silver/

  GoldPrefix:
    Type: String
    Default: netflix/gold/

  SilverDatabase:
    Type: String
    Default: silver_db

  GoldDatabase:
    Type: String
    Default: gold_db_new

  SilverJobName:
    Type: String
    Default: netflix-silver-job

  GoldJobName:
    Type: String
    Default: netflix-gold-job

  SilverCrawlerName:
    Type: String
    Default: silver_conversion_crawler

  GoldCrawlerName:
    Type: String
    Default: gold_conversion_crawler

  SilverJobScriptKey:
    Type: String
    Default: scripts/silver_job.py

  GoldJobScriptKey:
    Type: String
    Default: scripts/gold_job.py

Resources:

  # -----------------------------
  # IAM Role for Glue
  # -----------------------------
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-NetflixGlueServiceRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: NetflixGlueS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

  # -----------------------------
  # Glue Databases
  # -----------------------------
  SilverGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref SilverDatabase

  GoldGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref GoldDatabase

  # -----------------------------
  # Silver Crawler (Raw -> Silver schema)
  # -----------------------------
  SilverCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "${AWS::StackName}-${SilverCrawlerName}"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref SilverDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${BucketName}/${RawPrefix}
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE

  # -----------------------------
  # Gold Crawler (Silver -> Gold schema)
  # -----------------------------
  GoldCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "${AWS::StackName}-${GoldCrawlerName}"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GoldDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${BucketName}/${SilverPrefix}
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE

  # -----------------------------
  # Silver Glue Job
  # -----------------------------
  SilverGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${AWS::StackName}-${SilverJobName}"
      Role: !GetAtt GlueServiceRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/${SilverJobScriptKey}
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub s3://${BucketName}/sparkHistoryLogs/
      ExecutionProperty:
        MaxConcurrentRuns: 1
      WorkerType: G.1X
      NumberOfWorkers: 2

  # -----------------------------
  # Gold Glue Job
  # -----------------------------
  GoldGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${AWS::StackName}-${GoldJobName}"
      Role: !GetAtt GlueServiceRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/${GoldJobScriptKey}
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub s3://${BucketName}/sparkHistoryLogs/
      ExecutionProperty:
        MaxConcurrentRuns: 1
      WorkerType: G.1X
      NumberOfWorkers: 2

  # -----------------------------
  # Glue Workflow Silver
  # -----------------------------
  SilverWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Sub "${AWS::StackName}-Silver_workflow"

  SilverTriggerCrawler:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${AWS::StackName}-SilverTriggerCrawler"
      Type: ON_DEMAND
      WorkflowName: !Sub "${AWS::StackName}-Silver_workflow"
      Actions:
        - CrawlerName: !Ref SilverCrawler

  SilverTriggerJob:
    Type: AWS::Glue::Trigger
    DependsOn: SilverCrawler
    Properties:
      Name: !Sub "${AWS::StackName}-SilverTriggerJob"
      Type: CONDITIONAL
      WorkflowName: !Sub "${AWS::StackName}-Silver_workflow"
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref SilverCrawler
            CrawlState: SUCCEEDED
      Actions:
        - JobName: !Ref SilverGlueJob

  # -----------------------------
  # Glue Workflow Gold
  # -----------------------------
  GoldWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Sub "${AWS::StackName}-Gold_workflow"

  GoldTriggerCrawler:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${AWS::StackName}-GoldTriggerCrawler"
      Type: ON_DEMAND
      WorkflowName: !Sub "${AWS::StackName}-Gold_workflow"
      Actions:
        - CrawlerName: !Ref GoldCrawler

  GoldTriggerJob:
    Type: AWS::Glue::Trigger
    DependsOn: GoldCrawler
    Properties:
      Name: !Sub "${AWS::StackName}-GoldTriggerJob"
      Type: CONDITIONAL
      WorkflowName: !Sub "${AWS::StackName}-Gold_workflow"
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref GoldCrawler
            CrawlState: SUCCEEDED
      Actions:
        - JobName: !Ref GoldGlueJob

  # -----------------------------
  # IAM Role for EventBridge to start Glue Workflows
  # -----------------------------
  EventBridgeInvokeGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-NetflixEventBridgeInvokeGlueRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowStartGlueWorkflow
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartWorkflowRun
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${AWS::StackName}-Silver_workflow
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${AWS::StackName}-Gold_workflow

  # -----------------------------
  # CloudTrail Bucket for Logs
  # -----------------------------
  CloudTrailLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CloudTrailLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${CloudTrailLogsBucket}
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${CloudTrailLogsBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  # -----------------------------
  # CloudTrail: Enable S3 data events (required for EventBridge)
  # -----------------------------
  NetflixCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Sub "${AWS::StackName}-S3DataEventsTrail"
      IsLogging: true
      S3BucketName: !Ref CloudTrailLogsBucket
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: false
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: WriteOnly
          IncludeManagementEvents: true
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub arn:aws:s3:::${BucketName}/

  # -----------------------------
  # EventBridge Rule #1 RAW Upload -> Start Silver Workflow
  # -----------------------------
  RawUploadTriggerSilverRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-RawUploadTriggerSilverRule"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - PutObject
            - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - !Ref BucketName
            key:
              - prefix: !Ref RawPrefix
      Targets:
        - Arn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${AWS::StackName}-Silver_workflow
          Id: StartSilverWorkflow
          RoleArn: !GetAtt EventBridgeInvokeGlueRole.Arn

  # -----------------------------
  # EventBridge Rule #2 Silver _SUCCESS -> Start Gold Workflow
  # -----------------------------
  SilverSuccessTriggerGoldRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-SilverSuccessTriggerGoldRule"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - PutObject
          requestParameters:
            bucketName:
              - !Ref BucketName
            key:
              - prefix: !Sub ${SilverPrefix}_SUCCESS
      Targets:
        - Arn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${AWS::StackName}-Gold_workflow
          Id: StartGoldWorkflow
          RoleArn: !GetAtt EventBridgeInvokeGlueRole.Arn

Outputs:
  SilverWorkflowOut:
    Value: !Sub "${AWS::StackName}-Silver_workflow"
    Description: Silver Glue Workflow Name

  GoldWorkflowOut:
    Value: !Sub "${AWS::StackName}-Gold_workflow"
    Description: Gold Glue Workflow Name

  RawRuleOut:
    Value: !Ref RawUploadTriggerSilverRule
    Description: EventBridge Rule for RAW Upload -> Silver

  GoldRuleOut:
    Value: !Ref SilverSuccessTriggerGoldRule
    Description: EventBridge Rule for Silver Success -> Gold
